development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: transyug.com
  pool: 5
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: transyug.com
  pool: 5
  username: root
  password:
